// AUTO-PORTED from client/src/louda/LoudaApp.jsx lines 2722-3176 (GIPHY keys, emoji DB, categories, sticker DB).
export type EmojiItem = { emoji: string; name: string; tags: string[] };
export type EmojiCategory = { label: string; range: number[] };
export type StickerItem = { id: string; tags: string[]; url: string };
export const GIPHY_API_KEY = "1PsuVrcwCRiOYQEfqgPOd9kVuoRmuhai";
export const GIPHY_API_BASE = "https://api.giphy.com/v1/gifs";
export const MAX_TEXTAREA_HEIGHT = 180;

export const ALL_EMOJIS: EmojiItem[] = [
  // Smileys & Emotion
  { emoji: "😀", name: "grinning face", tags: ["happy", "smile", "grin"] },
  { emoji: "😃", name: "grinning face with big eyes", tags: ["happy", "smile"] },
  { emoji: "😄", name: "grinning face with smiling eyes", tags: ["happy", "smile", "joy"] },
  { emoji: "😁", name: "beaming face with smiling eyes", tags: ["grin", "happy"] },
  { emoji: "😆", name: "grinning squinting face", tags: ["laugh", "funny"] },
  { emoji: "😅", name: "grinning face with sweat", tags: ["nervous", "sweat"] },
  { emoji: "🤣", name: "rolling on the floor laughing", tags: ["rofl", "laugh", "lol"] },
  { emoji: "😂", name: "face with tears of joy", tags: ["lol", "laugh", "cry", "funny"] },
  { emoji: "🙂", name: "slightly smiling face", tags: ["smile", "happy"] },
  { emoji: "🙃", name: "upside-down face", tags: ["silly", "sarcasm"] },
  { emoji: "😉", name: "winking face", tags: ["wink", "flirt"] },
  { emoji: "😊", name: "smiling face with smiling eyes", tags: ["happy", "blush"] },
  { emoji: "😇", name: "smiling face with halo", tags: ["angel", "innocent"] },
  { emoji: "🥰", name: "smiling face with hearts", tags: ["love", "heart", "crush"] },
  { emoji: "😍", name: "smiling face with heart-eyes", tags: ["love", "heart", "adore"] },
  { emoji: "🤩", name: "star-struck", tags: ["wow", "star", "amazing"] },
  { emoji: "😘", name: "face blowing a kiss", tags: ["kiss", "love", "flirt"] },
  { emoji: "😗", name: "kissing face", tags: ["kiss"] },
  { emoji: "😚", name: "kissing face with closed eyes", tags: ["kiss"] },
  { emoji: "😙", name: "kissing face with smiling eyes", tags: ["kiss", "happy"] },
  { emoji: "🥲", name: "smiling face with tear", tags: ["happy", "sad", "bittersweet"] },
  { emoji: "😋", name: "face savoring food", tags: ["yummy", "food", "delicious"] },
  { emoji: "😛", name: "face with tongue", tags: ["tongue", "silly"] },
  { emoji: "😜", name: "winking face with tongue", tags: ["silly", "wink", "tongue"] },
  { emoji: "🤪", name: "zany face", tags: ["crazy", "silly", "wild"] },
  { emoji: "😝", name: "squinting face with tongue", tags: ["tongue", "funny"] },
  { emoji: "🤑", name: "money-mouth face", tags: ["money", "rich", "greedy"] },
  { emoji: "🤗", name: "hugging face", tags: ["hug", "warm", "love"] },
  { emoji: "🤭", name: "face with hand over mouth", tags: ["oops", "secret", "surprise"] },
  { emoji: "🤫", name: "shushing face", tags: ["shh", "quiet", "secret"] },
  { emoji: "🤔", name: "thinking face", tags: ["think", "hmm", "wonder"] },
  { emoji: "🤐", name: "zipper-mouth face", tags: ["silent", "secret", "zip"] },
  { emoji: "🤨", name: "face with raised eyebrow", tags: ["doubt", "skeptical", "suspicious"] },
  { emoji: "😐", name: "neutral face", tags: ["neutral", "meh", "blank"] },
  { emoji: "😑", name: "expressionless face", tags: ["blank", "expressionless", "meh"] },
  { emoji: "😶", name: "face without mouth", tags: ["silent", "speechless"] },
  { emoji: "😏", name: "smirking face", tags: ["smirk", "sly", "flirt"] },
  { emoji: "😒", name: "unamused face", tags: ["unamused", "bored", "whatever"] },
  { emoji: "🙄", name: "face with rolling eyes", tags: ["eyeroll", "whatever", "annoyed"] },
  { emoji: "😬", name: "grimacing face", tags: ["grimace", "awkward", "yikes"] },
  { emoji: "🤥", name: "lying face", tags: ["lie", "pinocchio"] },
  { emoji: "😌", name: "relieved face", tags: ["relieved", "peaceful", "calm"] },
  { emoji: "😔", name: "pensive face", tags: ["sad", "pensive", "thinking"] },
  { emoji: "😪", name: "sleepy face", tags: ["sleepy", "tired"] },
  { emoji: "🤤", name: "drooling face", tags: ["drool", "food", "yummy"] },
  { emoji: "😴", name: "sleeping face", tags: ["sleep", "zzz", "tired"] },
  { emoji: "😷", name: "face with medical mask", tags: ["sick", "mask", "ill"] },
  { emoji: "🤒", name: "face with thermometer", tags: ["sick", "fever", "ill"] },
  { emoji: "🤕", name: "face with head-bandage", tags: ["hurt", "injured", "bandage"] },
  { emoji: "🤢", name: "nauseated face", tags: ["sick", "nausea", "gross"] },
  { emoji: "🤮", name: "face vomiting", tags: ["vomit", "sick", "gross"] },
  { emoji: "🤧", name: "sneezing face", tags: ["sneeze", "sick", "cold"] },
  { emoji: "🥵", name: "hot face", tags: ["hot", "fire", "sweating"] },
  { emoji: "🥶", name: "cold face", tags: ["cold", "freezing", "ice"] },
  { emoji: "🥴", name: "woozy face", tags: ["dizzy", "woozy", "drunk"] },
  { emoji: "😵", name: "dizzy face", tags: ["dizzy", "confused", "shocked"] },
  { emoji: "🤯", name: "exploding head", tags: ["mind blown", "wow", "shock"] },
  { emoji: "🤠", name: "cowboy hat face", tags: ["cowboy", "western", "cool"] },
  { emoji: "🥳", name: "partying face", tags: ["party", "celebrate", "fun"] },
  { emoji: "🥸", name: "disguised face", tags: ["disguise", "glasses", "secret"] },
  { emoji: "😎", name: "smiling face with sunglasses", tags: ["cool", "sunglasses", "chill"] },
  { emoji: "🤓", name: "nerd face", tags: ["nerd", "geek", "smart"] },
  { emoji: "🧐", name: "face with monocle", tags: ["monocle", "fancy", "smart"] },
  { emoji: "😕", name: "confused face", tags: ["confused", "unsure", "hmm"] },
  { emoji: "😟", name: "worried face", tags: ["worried", "anxious", "concerned"] },
  { emoji: "🙁", name: "slightly frowning face", tags: ["sad", "frown"] },
  { emoji: "☹️", name: "frowning face", tags: ["sad", "frown", "unhappy"] },
  { emoji: "😮", name: "face with open mouth", tags: ["surprised", "wow", "shock"] },
  { emoji: "😯", name: "hushed face", tags: ["surprised", "shocked", "quiet"] },
  { emoji: "😲", name: "astonished face", tags: ["wow", "shocked", "astonished"] },
  { emoji: "😳", name: "flushed face", tags: ["flushed", "embarrassed", "shy"] },
  { emoji: "🥺", name: "pleading face", tags: ["plead", "puppy eyes", "cute", "sad"] },
  { emoji: "😦", name: "frowning face with open mouth", tags: ["sad", "shocked"] },
  { emoji: "😧", name: "anguished face", tags: ["anguish", "pain", "distress"] },
  { emoji: "😨", name: "fearful face", tags: ["fear", "scared", "afraid"] },
  { emoji: "😰", name: "anxious face with sweat", tags: ["nervous", "sweat", "anxious"] },
  { emoji: "😥", name: "sad but relieved face", tags: ["sad", "relieved", "whew"] },
  { emoji: "😢", name: "crying face", tags: ["cry", "sad", "tear"] },
  { emoji: "😭", name: "loudly crying face", tags: ["cry", "sob", "sad", "tears"] },
  { emoji: "😱", name: "face screaming in fear", tags: ["scream", "scared", "horror"] },
  { emoji: "😖", name: "confounded face", tags: ["confused", "frustrated", "stressed"] },
  { emoji: "😣", name: "persevering face", tags: ["struggle", "persevere", "hard"] },
  { emoji: "😞", name: "disappointed face", tags: ["disappointed", "sad", "down"] },
  { emoji: "😓", name: "downcast face with sweat", tags: ["disappointed", "hard", "sweat"] },
  { emoji: "😩", name: "weary face", tags: ["tired", "weary", "exhausted"] },
  { emoji: "😫", name: "tired face", tags: ["tired", "exhausted", "weary"] },
  { emoji: "🥱", name: "yawning face", tags: ["yawn", "tired", "bored"] },
  { emoji: "😤", name: "face with steam from nose", tags: ["angry", "frustrated", "steam"] },
  { emoji: "😡", name: "enraged face", tags: ["angry", "rage", "mad"] },
  { emoji: "😠", name: "angry face", tags: ["angry", "mad", "grumpy"] },
  { emoji: "🤬", name: "face with symbols on mouth", tags: ["angry", "swear", "rage"] },
  { emoji: "😈", name: "smiling face with horns", tags: ["devil", "evil", "mischievous"] },
  { emoji: "👿", name: "angry face with horns", tags: ["devil", "angry", "evil"] },
  { emoji: "💀", name: "skull", tags: ["dead", "skull", "death"] },
  { emoji: "☠️", name: "skull and crossbones", tags: ["dead", "danger", "skull"] },
  { emoji: "💩", name: "pile of poo", tags: ["poop", "funny", "crap"] },
  { emoji: "🤡", name: "clown face", tags: ["clown", "silly", "circus"] },
  { emoji: "👹", name: "ogre", tags: ["monster", "ogre", "scary"] },
  { emoji: "👺", name: "goblin", tags: ["goblin", "scary", "red"] },
  { emoji: "👻", name: "ghost", tags: ["ghost", "halloween", "boo"] },
  { emoji: "👽", name: "alien", tags: ["alien", "space", "ufo"] },
  { emoji: "👾", name: "alien monster", tags: ["alien", "game", "monster"] },
  { emoji: "🤖", name: "robot", tags: ["robot", "ai", "machine"] },
  // Hands & Body
  { emoji: "👋", name: "waving hand", tags: ["wave", "hi", "hello", "bye"] },
  { emoji: "🤚", name: "raised back of hand", tags: ["hand", "stop", "hi"] },
  { emoji: "🖐️", name: "hand with fingers splayed", tags: ["hand", "five", "hi"] },
  { emoji: "✋", name: "raised hand", tags: ["stop", "high five", "hand"] },
  { emoji: "🖖", name: "vulcan salute", tags: ["spock", "vulcan", "star trek"] },
  { emoji: "🫱", name: "rightwards hand", tags: ["hand", "right"] },
  { emoji: "🫲", name: "leftwards hand", tags: ["hand", "left"] },
  { emoji: "🫳", name: "palm down hand", tags: ["hand", "down"] },
  { emoji: "🫴", name: "palm up hand", tags: ["hand", "up", "offer"] },
  { emoji: "👌", name: "OK hand", tags: ["ok", "perfect", "fine"] },
  { emoji: "🤏", name: "pinching hand", tags: ["small", "tiny", "pinch"] },
  { emoji: "✌️", name: "victory hand", tags: ["peace", "victory", "v"] },
  { emoji: "🤞", name: "crossed fingers", tags: ["luck", "fingers crossed", "hope"] },
  { emoji: "🫰", name: "hand with index finger and thumb crossed", tags: ["snap", "cute"] },
  { emoji: "🤟", name: "love-you gesture", tags: ["love", "ily", "rock"] },
  { emoji: "🤘", name: "sign of the horns", tags: ["rock", "metal", "cool"] },
  { emoji: "🤙", name: "call me hand", tags: ["call", "shaka", "phone"] },
  { emoji: "👈", name: "backhand index pointing left", tags: ["point", "left", "this"] },
  { emoji: "👉", name: "backhand index pointing right", tags: ["point", "right", "this"] },
  { emoji: "👆", name: "backhand index pointing up", tags: ["point", "up"] },
  { emoji: "🖕", name: "middle finger", tags: ["middle", "rude", "finger"] },
  { emoji: "👇", name: "backhand index pointing down", tags: ["point", "down"] },
  { emoji: "☝️", name: "index pointing up", tags: ["one", "point", "up"] },
  { emoji: "🫵", name: "index pointing at the viewer", tags: ["you", "point"] },
  { emoji: "👍", name: "thumbs up", tags: ["good", "yes", "like", "approve"] },
  { emoji: "👎", name: "thumbs down", tags: ["bad", "no", "dislike"] },
  { emoji: "✊", name: "raised fist", tags: ["fist", "strong", "power"] },
  { emoji: "👊", name: "oncoming fist", tags: ["punch", "fist", "fight"] },
  { emoji: "🤛", name: "left-facing fist", tags: ["fist bump", "left"] },
  { emoji: "🤜", name: "right-facing fist", tags: ["fist bump", "right"] },
  { emoji: "👏", name: "clapping hands", tags: ["clap", "applause", "bravo"] },
  { emoji: "🙌", name: "raising hands", tags: ["celebrate", "yes", "raise"] },
  { emoji: "🫶", name: "heart hands", tags: ["love", "heart", "hands"] },
  { emoji: "👐", name: "open hands", tags: ["open", "hug", "welcome"] },
  { emoji: "🤲", name: "palms up together", tags: ["pray", "hands", "please"] },
  { emoji: "🤝", name: "handshake", tags: ["deal", "handshake", "agree"] },
  { emoji: "🙏", name: "folded hands", tags: ["pray", "please", "thanks", "namaste"] },
  { emoji: "✍️", name: "writing hand", tags: ["write", "pen", "note"] },
  { emoji: "💅", name: "nail polish", tags: ["nails", "fancy", "sassy"] },
  { emoji: "🤳", name: "selfie", tags: ["selfie", "phone", "photo"] },
  { emoji: "💪", name: "flexed biceps", tags: ["strong", "muscle", "gym"] },
  { emoji: "🦾", name: "mechanical arm", tags: ["robot", "arm", "strong"] },
  { emoji: "🦿", name: "mechanical leg", tags: ["robot", "leg"] },
  { emoji: "🦵", name: "leg", tags: ["leg", "kick"] },
  { emoji: "🦶", name: "foot", tags: ["foot", "feet"] },
  { emoji: "👂", name: "ear", tags: ["ear", "listen", "hearing"] },
  { emoji: "🦻", name: "ear with hearing aid", tags: ["ear", "hearing aid"] },
  { emoji: "👃", name: "nose", tags: ["nose", "smell"] },
  { emoji: "🫀", name: "anatomical heart", tags: ["heart", "organ", "medical"] },
  { emoji: "🫁", name: "lungs", tags: ["lungs", "breathe", "medical"] },
  { emoji: "🧠", name: "brain", tags: ["brain", "smart", "think"] },
  { emoji: "🦷", name: "tooth", tags: ["tooth", "teeth", "dental"] },
  { emoji: "🦴", name: "bone", tags: ["bone", "skeleton"] },
  { emoji: "👁️", name: "eye", tags: ["eye", "watch", "see"] },
  { emoji: "👀", name: "eyes", tags: ["eyes", "look", "watch", "stare"] },
  { emoji: "👅", name: "tongue", tags: ["tongue", "taste"] },
  { emoji: "👄", name: "mouth", tags: ["mouth", "lips", "kiss"] },
  { emoji: "🫦", name: "biting lip", tags: ["bite", "lip", "nervous", "flirt"] },
  // Hearts & Love
  { emoji: "❤️", name: "red heart", tags: ["love", "heart", "red"] },
  { emoji: "🧡", name: "orange heart", tags: ["love", "heart", "orange"] },
  { emoji: "💛", name: "yellow heart", tags: ["love", "heart", "yellow", "friend"] },
  { emoji: "💚", name: "green heart", tags: ["love", "heart", "green", "nature"] },
  { emoji: "💙", name: "blue heart", tags: ["love", "heart", "blue"] },
  { emoji: "💜", name: "purple heart", tags: ["love", "heart", "purple"] },
  { emoji: "🖤", name: "black heart", tags: ["love", "heart", "black", "dark"] },
  { emoji: "🤍", name: "white heart", tags: ["love", "heart", "white", "pure"] },
  { emoji: "🤎", name: "brown heart", tags: ["love", "heart", "brown"] },
  { emoji: "💔", name: "broken heart", tags: ["heartbreak", "sad", "broken"] },
  { emoji: "❤️‍🔥", name: "heart on fire", tags: ["passion", "love", "fire"] },
  { emoji: "❤️‍🩹", name: "mending heart", tags: ["healing", "broken", "love"] },
  { emoji: "❣️", name: "heart exclamation", tags: ["love", "heart", "exclamation"] },
  { emoji: "💕", name: "two hearts", tags: ["love", "hearts"] },
  { emoji: "💞", name: "revolving hearts", tags: ["love", "hearts", "romance"] },
  { emoji: "💓", name: "beating heart", tags: ["love", "heart", "beat"] },
  { emoji: "💗", name: "growing heart", tags: ["love", "heart", "grow"] },
  { emoji: "💖", name: "sparkling heart", tags: ["love", "heart", "sparkle"] },
  { emoji: "💘", name: "heart with arrow", tags: ["love", "cupid", "arrow"] },
  { emoji: "💝", name: "heart with ribbon", tags: ["love", "gift", "heart"] },
  { emoji: "💟", name: "heart decoration", tags: ["love", "heart", "purple"] },
  { emoji: "☮️", name: "peace symbol", tags: ["peace", "sign"] },
  { emoji: "✝️", name: "latin cross", tags: ["cross", "christian", "religion"] },
  { emoji: "☯️", name: "yin yang", tags: ["balance", "yin yang", "zen"] },
  { emoji: "🕊️", name: "dove", tags: ["peace", "dove", "bird"] },
  // Activities & Fun
  { emoji: "🎉", name: "party popper", tags: ["party", "celebrate", "confetti", "congrats"] },
  { emoji: "🎊", name: "confetti ball", tags: ["party", "celebrate", "confetti"] },
  { emoji: "🎈", name: "balloon", tags: ["balloon", "party", "celebrate"] },
  { emoji: "🎁", name: "wrapped gift", tags: ["gift", "present", "birthday"] },
  { emoji: "🎀", name: "ribbon", tags: ["ribbon", "gift", "bow"] },
  { emoji: "🎂", name: "birthday cake", tags: ["birthday", "cake", "celebrate"] },
  { emoji: "🎆", name: "fireworks", tags: ["fireworks", "celebrate", "new year"] },
  { emoji: "🎇", name: "sparkler", tags: ["sparkler", "celebrate", "new year"] },
  { emoji: "✨", name: "sparkles", tags: ["sparkle", "magic", "stars", "shine"] },
  { emoji: "🌟", name: "glowing star", tags: ["star", "shine", "wow"] },
  { emoji: "⭐", name: "star", tags: ["star", "favorite", "good"] },
  { emoji: "💫", name: "dizzy", tags: ["dizzy", "star", "sparkle"] },
  { emoji: "🔥", name: "fire", tags: ["fire", "hot", "lit", "flame"] },
  { emoji: "💥", name: "collision", tags: ["explosion", "bang", "boom"] },
  { emoji: "💢", name: "anger symbol", tags: ["angry", "mad"] },
  { emoji: "💦", name: "sweat droplets", tags: ["sweat", "water", "splash"] },
  { emoji: "💧", name: "droplet", tags: ["water", "drop", "rain"] },
  { emoji: "🏆", name: "trophy", tags: ["trophy", "win", "gold", "champion"] },
  { emoji: "🥇", name: "1st place medal", tags: ["gold", "first", "win", "medal"] },
  { emoji: "🥈", name: "2nd place medal", tags: ["silver", "second", "medal"] },
  { emoji: "🥉", name: "3rd place medal", tags: ["bronze", "third", "medal"] },
  { emoji: "🏅", name: "sports medal", tags: ["medal", "win", "sports"] },
  { emoji: "🎯", name: "bullseye", tags: ["target", "bullseye", "aim", "goal"] },
  { emoji: "🎮", name: "video game", tags: ["game", "gaming", "play", "controller"] },
  { emoji: "🕹️", name: "joystick", tags: ["game", "joystick", "arcade"] },
  { emoji: "🎲", name: "game die", tags: ["dice", "game", "random"] },
  { emoji: "🧩", name: "puzzle piece", tags: ["puzzle", "game", "piece"] },
  { emoji: "♟️", name: "chess pawn", tags: ["chess", "game", "strategy"] },
  { emoji: "🎭", name: "performing arts", tags: ["theater", "drama", "art"] },
  { emoji: "🎨", name: "artist palette", tags: ["art", "paint", "creative"] },
  { emoji: "🎬", name: "clapper board", tags: ["movie", "film", "action"] },
  { emoji: "🎤", name: "microphone", tags: ["mic", "sing", "music", "karaoke"] },
  { emoji: "🎧", name: "headphone", tags: ["music", "headphones", "listen"] },
  { emoji: "🎵", name: "musical note", tags: ["music", "note", "song"] },
  { emoji: "🎶", name: "musical notes", tags: ["music", "notes", "song"] },
  { emoji: "🎸", name: "guitar", tags: ["guitar", "music", "rock"] },
  { emoji: "🎹", name: "musical keyboard", tags: ["piano", "keyboard", "music"] },
  { emoji: "🥁", name: "drum", tags: ["drum", "music", "beat"] },
  { emoji: "🎺", name: "trumpet", tags: ["trumpet", "music", "jazz"] },
  { emoji: "🎻", name: "violin", tags: ["violin", "music", "classical"] },
  // Sports
  { emoji: "⚽", name: "soccer ball", tags: ["soccer", "football", "ball", "sport"] },
  { emoji: "🏀", name: "basketball", tags: ["basketball", "ball", "sport", "nba"] },
  { emoji: "🏈", name: "american football", tags: ["football", "nfl", "sport"] },
  { emoji: "⚾", name: "baseball", tags: ["baseball", "sport", "ball"] },
  { emoji: "🥎", name: "softball", tags: ["softball", "sport"] },
  { emoji: "🎾", name: "tennis", tags: ["tennis", "sport", "ball"] },
  { emoji: "🏐", name: "volleyball", tags: ["volleyball", "sport", "ball"] },
  { emoji: "🏉", name: "rugby football", tags: ["rugby", "sport"] },
  { emoji: "🥏", name: "flying disc", tags: ["frisbee", "disc", "sport"] },
  { emoji: "🎱", name: "pool 8 ball", tags: ["pool", "billiards", "ball"] },
  { emoji: "🪃", name: "boomerang", tags: ["boomerang", "throw"] },
  { emoji: "🏓", name: "ping pong", tags: ["pingpong", "tabletennis", "sport"] },
  { emoji: "🏸", name: "badminton", tags: ["badminton", "sport"] },
  { emoji: "🥊", name: "boxing glove", tags: ["boxing", "fight", "sport"] },
  { emoji: "🥋", name: "martial arts uniform", tags: ["karate", "martial arts", "sport"] },
  { emoji: "⛳", name: "flag in hole", tags: ["golf", "sport"] },
  { emoji: "🏊", name: "person swimming", tags: ["swim", "pool", "sport"] },
  { emoji: "🚴", name: "person biking", tags: ["bike", "cycle", "sport"] },
  { emoji: "🏋️", name: "person lifting weights", tags: ["gym", "weights", "lift", "strong"] },
  { emoji: "🤸", name: "person cartwheeling", tags: ["gymnastics", "cartwheel", "sport"] },
  { emoji: "⛷️", name: "skier", tags: ["ski", "snow", "sport"] },
  { emoji: "🏄", name: "person surfing", tags: ["surf", "wave", "sport", "beach"] },
  // Food & Drink
  { emoji: "🍕", name: "pizza", tags: ["pizza", "food", "italian"] },
  { emoji: "🍔", name: "hamburger", tags: ["burger", "food", "fast food"] },
  { emoji: "🍟", name: "french fries", tags: ["fries", "food", "fast food"] },
  { emoji: "🌮", name: "taco", tags: ["taco", "food", "mexican"] },
  { emoji: "🌯", name: "burrito", tags: ["burrito", "food", "mexican"] },
  { emoji: "🥗", name: "green salad", tags: ["salad", "healthy", "food"] },
  { emoji: "🍣", name: "sushi", tags: ["sushi", "food", "japanese"] },
  { emoji: "🍜", name: "steaming bowl", tags: ["noodles", "ramen", "food"] },
  { emoji: "🍝", name: "spaghetti", tags: ["pasta", "spaghetti", "italian", "food"] },
  { emoji: "🍗", name: "poultry leg", tags: ["chicken", "food", "meat"] },
  { emoji: "🥩", name: "cut of meat", tags: ["steak", "meat", "food"] },
  { emoji: "🍿", name: "popcorn", tags: ["popcorn", "movie", "snack"] },
  { emoji: "🍩", name: "doughnut", tags: ["donut", "dessert", "sweet"] },
  { emoji: "🍪", name: "cookie", tags: ["cookie", "dessert", "sweet", "bake"] },
  { emoji: "🎂", name: "birthday cake", tags: ["cake", "birthday", "sweet"] },
  { emoji: "🍫", name: "chocolate bar", tags: ["chocolate", "sweet", "dessert"] },
  { emoji: "🍦", name: "soft ice cream", tags: ["ice cream", "dessert", "sweet"] },
  { emoji: "🧁", name: "cupcake", tags: ["cupcake", "sweet", "dessert", "bake"] },
  { emoji: "🍓", name: "strawberry", tags: ["strawberry", "fruit", "food"] },
  { emoji: "🍇", name: "grapes", tags: ["grapes", "fruit", "food"] },
  { emoji: "🍎", name: "red apple", tags: ["apple", "fruit", "food"] },
  { emoji: "🍊", name: "tangerine", tags: ["orange", "fruit", "food"] },
  { emoji: "🍋", name: "lemon", tags: ["lemon", "fruit", "sour"] },
  { emoji: "🍉", name: "watermelon", tags: ["watermelon", "fruit", "summer"] },
  { emoji: "🍑", name: "peach", tags: ["peach", "fruit", "food"] },
  { emoji: "🥑", name: "avocado", tags: ["avocado", "food", "healthy", "guac"] },
  { emoji: "🧀", name: "cheese wedge", tags: ["cheese", "food"] },
  { emoji: "🍳", name: "cooking", tags: ["egg", "cook", "breakfast", "food"] },
  { emoji: "☕", name: "hot beverage", tags: ["coffee", "tea", "hot", "drink"] },
  { emoji: "🧋", name: "bubble tea", tags: ["boba", "tea", "drink"] },
  { emoji: "🥤", name: "cup with straw", tags: ["drink", "soda", "juice"] },
  { emoji: "🍺", name: "beer mug", tags: ["beer", "drink", "cheers"] },
  { emoji: "🍻", name: "clinking beer mugs", tags: ["beer", "cheers", "drink"] },
  { emoji: "🥂", name: "clinking glasses", tags: ["champagne", "toast", "celebrate"] },
  { emoji: "🍷", name: "wine glass", tags: ["wine", "drink", "fancy"] },
  { emoji: "🧃", name: "beverage box", tags: ["juice", "drink", "box"] },
  { emoji: "🥛", name: "glass of milk", tags: ["milk", "drink", "white"] },
  // Travel & Places
  { emoji: "🚀", name: "rocket", tags: ["rocket", "space", "launch", "fast"] },
  { emoji: "🛸", name: "flying saucer", tags: ["ufo", "alien", "space"] },
  { emoji: "✈️", name: "airplane", tags: ["plane", "fly", "travel", "airport"] },
  { emoji: "🚗", name: "automobile", tags: ["car", "drive", "travel"] },
  { emoji: "🚕", name: "taxi", tags: ["taxi", "cab", "ride"] },
  { emoji: "🚌", name: "bus", tags: ["bus", "transit", "travel"] },
  { emoji: "🚂", name: "locomotive", tags: ["train", "travel", "steam"] },
  { emoji: "🚢", name: "ship", tags: ["ship", "boat", "cruise", "travel"] },
  { emoji: "🛳️", name: "passenger ship", tags: ["ship", "cruise", "ocean"] },
  { emoji: "🚁", name: "helicopter", tags: ["helicopter", "fly", "travel"] },
  { emoji: "🏍️", name: "motorcycle", tags: ["motorcycle", "bike", "ride"] },
  { emoji: "🚲", name: "bicycle", tags: ["bicycle", "bike", "ride", "eco"] },
  { emoji: "🛺", name: "auto rickshaw", tags: ["tuk tuk", "taxi", "india"] },
  { emoji: "🏠", name: "house", tags: ["home", "house", "building"] },
  { emoji: "🏢", name: "office building", tags: ["office", "work", "city"] },
  { emoji: "🏖️", name: "beach with umbrella", tags: ["beach", "summer", "vacation"] },
  { emoji: "🏔️", name: "snow-capped mountain", tags: ["mountain", "snow", "nature"] },
  { emoji: "🌴", name: "palm tree", tags: ["palm", "tropical", "beach"] },
  { emoji: "🗼", name: "Tokyo tower", tags: ["tokyo", "japan", "tower"] },
  { emoji: "🗽", name: "Statue of Liberty", tags: ["liberty", "usa", "statue"] },
  { emoji: "🗺️", name: "world map", tags: ["map", "world", "travel"] },
  { emoji: "🧭", name: "compass", tags: ["compass", "navigate", "direction"] },
  // Nature & Weather
  { emoji: "🌈", name: "rainbow", tags: ["rainbow", "colorful", "lgbtq", "hope"] },
  { emoji: "☀️", name: "sun", tags: ["sun", "sunny", "hot", "bright"] },
  { emoji: "🌤️", name: "sun behind small cloud", tags: ["partly cloudy", "sun", "weather"] },
  { emoji: "⛅", name: "sun behind cloud", tags: ["cloudy", "weather"] },
  { emoji: "🌧️", name: "cloud with rain", tags: ["rain", "weather", "cloud"] },
  { emoji: "⛈️", name: "cloud with lightning and rain", tags: ["storm", "lightning", "rain"] },
  { emoji: "🌩️", name: "cloud with lightning", tags: ["lightning", "storm", "thunder"] },
  { emoji: "❄️", name: "snowflake", tags: ["snow", "cold", "winter", "ice"] },
  { emoji: "🌙", name: "crescent moon", tags: ["moon", "night", "sleep"] },
  { emoji: "🌊", name: "water wave", tags: ["wave", "ocean", "sea", "surf"] },
  { emoji: "🌺", name: "hibiscus", tags: ["flower", "tropical", "nature"] },
  { emoji: "🌸", name: "cherry blossom", tags: ["flower", "pink", "spring", "japan"] },
  { emoji: "🌹", name: "rose", tags: ["rose", "flower", "love", "red"] },
  { emoji: "🌻", name: "sunflower", tags: ["sunflower", "flower", "yellow"] },
  { emoji: "🌿", name: "herb", tags: ["herb", "green", "nature", "leaf"] },
  { emoji: "🍀", name: "four leaf clover", tags: ["clover", "luck", "green"] },
  { emoji: "🌵", name: "cactus", tags: ["cactus", "desert", "plant"] },
  { emoji: "🐶", name: "dog face", tags: ["dog", "pet", "cute", "puppy"] },
  { emoji: "🐱", name: "cat face", tags: ["cat", "pet", "cute", "kitty"] },
  { emoji: "🐭", name: "mouse face", tags: ["mouse", "small", "cute"] },
  { emoji: "🐹", name: "hamster", tags: ["hamster", "cute", "pet"] },
  { emoji: "🐰", name: "rabbit face", tags: ["rabbit", "bunny", "cute"] },
  { emoji: "🦊", name: "fox", tags: ["fox", "sly", "cute"] },
  { emoji: "🐻", name: "bear", tags: ["bear", "animal", "cute"] },
  { emoji: "🐼", name: "panda", tags: ["panda", "cute", "china", "bear"] },
  { emoji: "🐨", name: "koala", tags: ["koala", "australia", "cute"] },
  { emoji: "🐯", name: "tiger face", tags: ["tiger", "wild", "animal"] },
  { emoji: "🦁", name: "lion", tags: ["lion", "king", "roar"] },
  { emoji: "🐮", name: "cow face", tags: ["cow", "animal", "farm"] },
  { emoji: "🐷", name: "pig face", tags: ["pig", "animal", "cute"] },
  { emoji: "🐸", name: "frog", tags: ["frog", "green", "ribbit"] },
  { emoji: "🐵", name: "monkey face", tags: ["monkey", "animal", "silly"] },
  { emoji: "🐧", name: "penguin", tags: ["penguin", "cute", "bird"] },
  { emoji: "🐦", name: "bird", tags: ["bird", "tweet", "animal"] },
  { emoji: "🦆", name: "duck", tags: ["duck", "quack", "bird"] },
  { emoji: "🦅", name: "eagle", tags: ["eagle", "bird", "freedom"] },
  { emoji: "🦋", name: "butterfly", tags: ["butterfly", "beautiful", "nature"] },
  { emoji: "🐝", name: "honeybee", tags: ["bee", "honey", "insect"] },
  { emoji: "🐢", name: "turtle", tags: ["turtle", "slow", "animal"] },
  { emoji: "🐬", name: "dolphin", tags: ["dolphin", "ocean", "smart"] },
  { emoji: "🐳", name: "spouting whale", tags: ["whale", "ocean", "animal"] },
  { emoji: "🦈", name: "shark", tags: ["shark", "ocean", "scary", "fish"] },
  { emoji: "🐙", name: "octopus", tags: ["octopus", "ocean", "tentacles"] },
  { emoji: "🦁", name: "lion", tags: ["lion", "roar", "king"] },
  // Objects & Tech
  { emoji: "📱", name: "mobile phone", tags: ["phone", "mobile", "call", "text"] },
  { emoji: "💻", name: "laptop", tags: ["laptop", "computer", "work", "code"] },
  { emoji: "⌨️", name: "keyboard", tags: ["keyboard", "type", "computer"] },
  { emoji: "🖥️", name: "desktop computer", tags: ["computer", "desktop", "monitor"] },
  { emoji: "🖨️", name: "printer", tags: ["printer", "print", "office"] },
  { emoji: "⌚", name: "watch", tags: ["watch", "time", "clock"] },
  { emoji: "📷", name: "camera", tags: ["camera", "photo", "picture"] },
  { emoji: "📹", name: "video camera", tags: ["video", "camera", "record"] },
  { emoji: "📺", name: "television", tags: ["tv", "television", "watch"] },
  { emoji: "📻", name: "radio", tags: ["radio", "music", "listen"] },
  { emoji: "📡", name: "satellite antenna", tags: ["satellite", "signal", "wifi"] },
  { emoji: "🔋", name: "battery", tags: ["battery", "power", "charge"] },
  { emoji: "🔌", name: "electric plug", tags: ["plug", "power", "charge"] },
  { emoji: "💡", name: "light bulb", tags: ["idea", "light", "bright", "bulb"] },
  { emoji: "🔦", name: "flashlight", tags: ["flashlight", "torch", "light"] },
  { emoji: "🕯️", name: "candle", tags: ["candle", "light", "flame"] },
  { emoji: "📖", name: "open book", tags: ["book", "read", "story"] },
  { emoji: "📚", name: "books", tags: ["books", "read", "study"] },
  { emoji: "📝", name: "memo", tags: ["note", "write", "memo"] },
  { emoji: "📌", name: "pushpin", tags: ["pin", "mark", "location"] },
  { emoji: "📎", name: "paperclip", tags: ["clip", "attach", "paper"] },
  { emoji: "✂️", name: "scissors", tags: ["scissors", "cut"] },
  { emoji: "🔑", name: "key", tags: ["key", "lock", "access"] },
  { emoji: "🔒", name: "locked", tags: ["lock", "secure", "private"] },
  { emoji: "🔓", name: "unlocked", tags: ["unlock", "open", "access"] },
  { emoji: "💰", name: "money bag", tags: ["money", "rich", "cash", "gold"] },
  { emoji: "💳", name: "credit card", tags: ["card", "pay", "money"] },
  { emoji: "💎", name: "gem stone", tags: ["diamond", "gem", "rich", "sparkle"] },
  { emoji: "🛒", name: "shopping cart", tags: ["shop", "cart", "buy"] },
  { emoji: "🎁", name: "gift", tags: ["gift", "present", "birthday"] },
  { emoji: "🎒", name: "backpack", tags: ["backpack", "school", "bag"] },
  { emoji: "👓", name: "glasses", tags: ["glasses", "nerd", "see"] },
  { emoji: "🕶️", name: "sunglasses", tags: ["sunglasses", "cool", "sun"] },
  { emoji: "🧢", name: "billed cap", tags: ["cap", "hat", "fashion"] },
  { emoji: "👑", name: "crown", tags: ["crown", "king", "queen", "royal"] },
  { emoji: "💍", name: "ring", tags: ["ring", "wedding", "diamond", "love"] },
  { emoji: "👙", name: "bikini", tags: ["bikini", "beach", "summer"] },
  { emoji: "🩴", name: "thong sandal", tags: ["sandal", "summer", "beach"] },
  // Symbols & Signs
  { emoji: "✅", name: "check mark button", tags: ["check", "done", "yes", "tick"] },
  { emoji: "❌", name: "cross mark", tags: ["no", "wrong", "cross", "cancel"] },
  { emoji: "⚡", name: "high voltage", tags: ["lightning", "electric", "fast", "power"] },
  { emoji: "🚨", name: "police car light", tags: ["alert", "warning", "alarm", "police"] },
  { emoji: "⚠️", name: "warning", tags: ["warning", "caution", "danger"] },
  { emoji: "🚫", name: "prohibited", tags: ["no", "stop", "forbidden", "banned"] },
  { emoji: "♻️", name: "recycling symbol", tags: ["recycle", "eco", "green"] },
  { emoji: "💯", name: "hundred points", tags: ["100", "perfect", "score", "yes"] },
  { emoji: "🔥", name: "fire", tags: ["fire", "hot", "lit", "trending"] },
  { emoji: "💬", name: "speech bubble", tags: ["chat", "message", "talk", "speech"] },
  { emoji: "💭", name: "thought balloon", tags: ["thought", "think", "dream"] },
  { emoji: "🗨️", name: "left speech bubble", tags: ["chat", "message", "speech"] },
  { emoji: "📣", name: "megaphone", tags: ["announce", "loud", "megaphone"] },
  { emoji: "📢", name: "loudspeaker", tags: ["speaker", "loud", "announce"] },
  { emoji: "🔔", name: "bell", tags: ["bell", "notification", "ring"] },
  { emoji: "🔕", name: "bell with slash", tags: ["silent", "mute", "no sound"] },
  { emoji: "🎵", name: "musical note", tags: ["music", "note", "song"] },
  { emoji: "🎶", name: "musical notes", tags: ["music", "notes", "song"] },
  { emoji: "🆕", name: "NEW button", tags: ["new", "fresh"] },
  { emoji: "🆙", name: "UP button", tags: ["up", "upgrade"] },
  { emoji: "🆒", name: "COOL button", tags: ["cool", "awesome"] },
  { emoji: "🆓", name: "FREE button", tags: ["free", "gratis"] },
  { emoji: "🔝", name: "TOP arrow", tags: ["top", "best", "up"] },
  { emoji: "🏳️", name: "white flag", tags: ["flag", "peace", "surrender"] },
  { emoji: "🏴", name: "black flag", tags: ["flag", "dark"] },
  { emoji: "🏁", name: "chequered flag", tags: ["finish", "race", "done"] },
  { emoji: "🚩", name: "triangular flag", tags: ["flag", "alert", "mark"] },
];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { label: "😀 Smileys", range: [0, 79] },
  { label: "👋 Hands", range: [80, 119] },
  { label: "❤️ Hearts", range: [120, 145] },
  { label: "🎉 Fun", range: [146, 185] },
  { label: "⚽ Sports", range: [186, 205] },
  { label: "🍕 Food", range: [206, 245] },
  { label: "🚀 Travel", range: [246, 268] },
  { label: "🌈 Nature", range: [269, 315] },
  { label: "📱 Objects", range: [316, 360] },
  { label: "✅ Symbols", range: [361, 999] },
];

export const STICKERS_DB: StickerItem[] = [
  { id: "yes", tags: ["yes", "agree", "nod"], url: "https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif" },
  { id: "no", tags: ["no", "deny", "shake"], url: "https://media.giphy.com/media/15aGGXfSlat2dP6ohs/giphy.gif" },
  { id: "laugh", tags: ["laugh", "lol", "funny"], url: "https://media.giphy.com/media/l0HlO3BJ8LALPW4sE/giphy.gif" },
  { id: "cry", tags: ["cry", "sad", "tears"], url: "https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif" },
  { id: "angry", tags: ["angry", "mad", "rage"], url: "https://media.giphy.com/media/11tTNkNy1SdXGg/giphy.gif" },
  { id: "wow", tags: ["wow", "omg", "surprise"], url: "https://media.giphy.com/media/5wWf7GMbT1ZUGTDdTqM/giphy.gif" },
  { id: "love", tags: ["love", "heart", "romance"], url: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif" }
];
